#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate README.md / README.zh-CN.md / assets/hot.svg from the data files.

    data/projects.json   ← the list itself (categories, entries, reasons)
    data/stars.json      ← refreshed by fetch_stars.py

⛔ Never hand-edit README.md. Any number in it comes from here.
Badges are live shields.io images, so star counts never go stale even
if this script is not run.
"""
import json, os, re, sys, html, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = lambda *p: os.path.join(ROOT, *p)

S = lambda n, f="stars": (
    f"https://img.shields.io/github/{f}/{n}?style=flat&logo=github&label=")


def badge(n):
    return (f'<img src="{S(n)}" alt="stars"> '
            f'<img src="{S(n, "created-at")}" alt="created">')


def anchors(cats):
    return " · ".join(
        f'<a href="#{c["id"]}">{c["emoji"]} {c["title_en"]}</a>' for c in cats)


def body(cats, stars, zh):
    """Render the category sections. zh=False → English."""
    out = []
    for c in cats:
        title = c["title_zh"] if zh else c["title_en"]
        note = c["note_zh"] if zh else c["note_en"]
        out.append(f'<h2 id="{c["id"]}">{c["emoji"]} {title}'
                   f' <sub>{len(c["items"])}</sub></h2>')
        out.append(f'<p><em>{note}</em></p>')
        for it in c["items"]:
            n = it["repo"]
            reason = it["reason_zh"] if zh else it["reason_en"]
            st = stars.get(n, {})
            line = [f'- **[{n}](https://github.com/{n})** {badge(n)}']
            if st.get("created"):
                line.append(f'  <sub>created {st["created"]}'
                            + (f' · {st["stars"]}★' if st.get("stars") is not None else "")
                            + '</sub>')
            if reason:
                line.append(f'  <br>{reason}')
            out.append("\n".join(line))
        out.append("")
    return "\n".join(out)


def hot_table(stars, cats, zh=False):
    """Ranked by real stars. Computed, never written by hand."""
    known = {i["repo"] for c in cats for i in c["items"]}
    rows = sorted(((n, s) for n, s in stars.items() if n in known),
                  key=lambda kv: -kv[1].get("stars", 0))[:10]
    head = ("| # | Project | Stars | Created |" if not zh else
            "| # | 项目 | 星数 | 创建 |")
    out = [head, "|---|---|---|---|"]
    for i, (n, s) in enumerate(rows, 1):
        out.append(f'| {i} | **[{n}](https://github.com/{n})** '
                   f'| <img src="{S(n)}" alt="stars"> '
                   f'| <img src="{S(n, "created-at")}" alt="created"> |')
    return "\n".join(out)


def howto(cats, zh):
    if zh:
        return ("**想搞懂 Jev** → `browser-use/jev-ultrafast`。"
                "生态里最大的一次成本削减，看它怎么写那一次判定。\n\n"
                "**想明天就能用上** → Claude Code 上用 `tamaratran/fast-jev-compaction`，"
                "浏览器自动化用 `browser-use/jev-ultrafast`。\n\n"
                "**想自己做一个** → 从 `kerpopule/hermes-jev-skills` 起步，"
                "回路已经接好了。")
    return ("**Want to understand Jev** → `browser-use/jev-ultrafast`. "
            "The biggest cost cut in the ecosystem — read how the single decision is made.\n\n"
            "**Want to use it tomorrow** → `tamaratran/fast-jev-compaction` for Claude Code, "
            "`browser-use/jev-ultrafast` for browser automation.\n\n"
            "**Want to ship your own** → start from `kerpopule/hermes-jev-skills`; "
            "the loop is already wired.")


def render(cats, stars, zh):
    n_total = sum(len(c["items"]) for c in cats)
    n_with = sum(1 for c in cats for i in c["items"]
                 if (i["reason_zh"] if zh else i["reason_en"]))
    if zh:
        title = "awesome-jev-essentials"
        tag = "**真正值得你花时间的 Jev 项目** —— 挑过、比过、持续更新。"
        toc = "## 目录"
        hot_h = "## 📈 热门项目（按星数自动排序）"
        hot_note = (f"由 `scripts/gen_readme.py` 从 `data/stars.json` 生成。"
                    f"⛔ 不手写。星数即便脚本没跑也不会过期——徽章是实时的。")
        why_h = "## 🧭 怎么选"
        foot = (f"收录 {n_total} 个，覆盖 {len(cats)} 类；"
                f"其中 {n_with} 个已写选它的理由，其余理由在补。\n\n")
        lang = "**English** · [中文](README.zh-CN.md)"
    else:
        title = "awesome-jev-essentials"
        tag = "**The Jev projects actually worth your time** — picked, compared, kept current."
        toc = "## Contents"
        hot_h = "## 📈 Most starred (ranked automatically)"
        hot_note = (f"Generated by `scripts/gen_readme.py` from `data/stars.json`. "
                    f"⛔ Never hand-edited. Counts cannot go stale — the badges are live.")
        why_h = "## 🧭 How to choose"
        foot = (f"{n_total} projects across {len(cats)} categories; "
                f"{n_with} have a written reason, the rest are being written.\n\n")
        lang = "**English** · [中文](README.zh-CN.md)"
    if zh:
        claim = "🔴 **每个条目都写了「为什么选它」，这件事本身就是内容** ——"
        claim2 = "只列名字的清单，GitHub 搜索一秒钟就能生成一份，那份清单就值那么多。"
    else:
        claim = "🔴 **Writing a \"why this one\" for every entry is the work** —"
        claim2 = ("a list of bare names is what a GitHub search produces "
                  "in one second, and it is worth exactly that.")
    return f"""# {title}

{tag}

{lang}

{toc}

{anchors(cats)} · <a href="#hot">📈 {"热门" if zh else "Most starred"}</a> · <a href="#choose">🧭 {"怎么选" if zh else "How to choose"}</a>

---

{body(cats, stars, zh)}
<h2 id="hot">{hot_h[3:]}</h2>

<em>{hot_note}</em>

{hot_table(stars, cats, zh)}

---

<h2 id="choose">{why_h[3:]}</h2>

{howto(cats, zh)}

---

### {"关于" if zh else "About"}

{foot}{claim}
{claim2}
"""


def main():
    cats = json.load(open(D("data", "projects.json")))["categories"]
    try:
        stars = json.load(open(D("data", "stars.json")))
    except FileNotFoundError:
        print("⚠️  data/stars.json 不在 —— 先跑 scripts/fetch_stars.py")
        stars = {}
    for lang, zh in (("README.md", False), ("README.zh-CN.md", True)):
        open(D(lang), "w").write(render(cats, stars, zh))
        print(f"✅ {lang}")
    os.makedirs(D("assets"), exist_ok=True)
    write_banner(cats, stars)


def write_banner(cats, stars):
    """Title image. The concept: many paths, only three lit — that is 'essentials'."""
    total = sum(len(c["items"]) for c in cats)
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 300" width="1200" height="300" role="img" aria-label="awesome-jev-essentials">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#080b17"/><stop offset="50%" stop-color="#101529"/><stop offset="100%" stop-color="#171233"/>
    </linearGradient>
    <linearGradient id="acc" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="#5eead4"/><stop offset="55%" stop-color="#8b9cf8"/><stop offset="100%" stop-color="#c084fc"/>
    </linearGradient>
    <linearGradient id="acc2" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="#5eead4" stop-opacity="0.8"/><stop offset="100%" stop-color="#818cf8" stop-opacity="0.5"/>
    </linearGradient>
    <radialGradient id="glow" cx="0.74" cy="0.5" r="0.48">
      <stop offset="0%" stop-color="#8b9cf8" stop-opacity="0.22"/><stop offset="100%" stop-color="#8b9cf8" stop-opacity="0"/>
    </radialGradient>
    <pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse">
      <path d="M24 0 H0 V24" fill="none" stroke="#ffffff" stroke-opacity="0.032" stroke-width="1"/>
    </pattern>
    <filter id="gl" x="-60%" y="-60%" width="220%" height="220%">
      <feGaussianBlur stdDeviation="5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge>
    </filter>
    <filter id="gls" x="-60%" y="-60%" width="220%" height="220%">
      <feGaussianBlur stdDeviation="2.6" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge>
    </filter>
  </defs>
  <rect width="1200" height="300" fill="url(#bg)"/>
  <rect width="1200" height="300" fill="url(#grid)"/>
  <rect width="1200" height="300" fill="url(#glow)"/>
  <g fill="none" stroke-linecap="round">
    <g stroke="#212a42" stroke-width="1.5">
      <path d="M812 150 C 880 150 930 34  1150 34"/><path d="M812 150 C 880 150 930 90  1150 90"/>
      <path d="M812 150 C 880 150 930 122 1150 122"/><path d="M812 150 C 880 150 930 178 1150 178"/>
      <path d="M812 150 C 880 150 930 210 1150 210"/><path d="M812 150 C 880 150 930 266 1150 266"/>
    </g>
    <g filter="url(#gl)">
      <path d="M812 150 C 880 150 930 62  1150 62"  stroke="url(#acc)" stroke-width="3.2" opacity="0.95"/>
      <path d="M812 150 C 880 150 930 150 1150 150" stroke="url(#acc)" stroke-width="3.2" opacity="0.95"/>
      <path d="M812 150 C 880 150 930 238 1150 238" stroke="url(#acc)" stroke-width="3.2" opacity="0.95"/>
    </g>
    <g stroke="url(#acc2)" stroke-width="1.7" opacity="0.55">
      <path d="M1002 62  C 1052 62  1062 44  1150 44"/><path d="M1002 62  C 1052 62  1062 80  1150 80"/>
      <path d="M1002 150 C 1052 150 1062 132 1150 132"/><path d="M1002 150 C 1052 150 1062 168 1150 168"/>
      <path d="M1002 238 C 1052 238 1062 220 1150 220"/><path d="M1002 238 C 1052 238 1062 256 1150 256"/>
    </g>
  </g>
  <circle cx="812" cy="150" r="16" fill="#080b17" stroke="url(#acc)" stroke-width="3" filter="url(#gls)"/>
  <circle cx="812" cy="150" r="5.5" fill="url(#acc)"/>
  <g filter="url(#gls)">
    <circle cx="1150" cy="62"  r="6" fill="#5eead4"/><circle cx="1150" cy="150" r="6" fill="#8b9cf8"/>
    <circle cx="1150" cy="238" r="6" fill="#c084fc"/>
  </g>
  <text x="72" y="118" font-family="ui-sans-serif,-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,PingFang SC,sans-serif"
        font-size="50" font-weight="700" fill="#f2f5ff" letter-spacing="-1.4">awesome-jev<tspan fill="#6b76a3">-</tspan><tspan fill="url(#acc)">essentials</tspan></text>
  <text x="74" y="160" font-family="ui-sans-serif,-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,PingFang SC,sans-serif"
        font-size="19" fill="#a9b3d6">The Jev projects actually worth your time.</text>
  <rect x="74" y="184" width="64" height="3" rx="1.5" fill="url(#acc)"/>
  <text x="74" y="216" font-family="ui-sans-serif,-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,PingFang SC,sans-serif"
        font-size="14.5" fill="#7a85ad">{total} projects, {len(cats)} categories. Not everything — just the ones we'd tell a friend to try.</text>
  <text x="74" y="246" font-family="ui-sans-serif,-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,PingFang SC,sans-serif"
        font-size="12.5" fill="#4e5878" letter-spacing="1.6">ENGLISH  ·  中文</text>
</svg>
'''
    open(D("assets", "banner.svg"), "w").write(svg)
    print("✅ assets/banner.svg")


if __name__ == "__main__":
    main()
